# **Etapa 0)** Importando a biblioteca NLTk - Importar todas!

In [ ]:
!pip install nltk
import nltk 
nltk.download()

In [ ]:
!pip install unidecode
!pip install unicodedata
import unidecode
import unicodedata
import numpy as np


# **Etapa 1)** Abrindo arquivos do drive

Arquivo de notícias **verdadeiras**

In [ ]:
corpus_true = open("/content/Verdadeiro.txt").readlines()
#print(corpus_true)

Arquivo de notícias **falsas**

In [ ]:
corpus_false = open("/content/falso.txt").read()
#print(corpus_false)

# **Etapa 2 - Tokenizar e calcular frequências**

**2.1)** Notícias **VERDADEIRAS:**

1) Sem pontuações

2) Sem números

3) Sem stop words

4) Em minúsculas

In [ ]:
#Retirando acentos Noticias Verdadeiras- Codificacao 

corpus_true_unicode = unidecode.unidecode(corpus_true)
print(corpus_true_unicode) 

In [ ]:
from nltk.tokenize import RegexpTokenizer
#Utilizando as stopwords do nltk
stopwords = nltk.corpus.stopwords.words('portuguese') 

#Método do nltk para considerar somente letras e retirar pontuação
tokenizer = RegexpTokenizer(r'[a-zA-Z]\w*') 
#Método do nltk para tokenizar palavras
tokens_true = tokenizer.tokenize(corpus_true_unicode)  

tokens_true_sem_stopwords = []
for token in tokens_true:
  # Remove as stopwords
  if token.lower() not in stopwords: 
    # Coloca os tokens em minúsculas, o que é imporante para a frequência
    tokens_true_sem_stopwords.append(token.lower()) 

#print(tokens_true_sem_stopwords)
frequencia_true = nltk.FreqDist(tokens_true_sem_stopwords)
frequencia_true.most_common(15)

In [ ]:
len(corpus_true)

In [ ]:
#Números calculados pela contagem total de palavras presentes no texto - Verdadeiro
n_words = len(tokens_true_sem_stopwords)
frequencia_true_relativa = list(map(lambda x: (x[0], x[1]/n_words), frequencia_true.most_common()))
frequencia_true_relativa
#sum([x[1] for x in frequencia_true_relativa])


**2.2)** Notícias **FALSAS**:

1) Sem pontuações

2) Sem números

3) Sem stop words

4) Em minúsculas

In [ ]:
#Retirando acentos Noticias Verdadeiras- Codificacao -- (Ainda em teste)

corpus_false_unicode = unidecode.unidecode(corpus_false)
print(corpus_false_unicode) 

In [ ]:
from nltk.tokenize import RegexpTokenizer
stopwords = nltk.corpus.stopwords.words('portuguese') #Utilizando as stopwords do nltk

tokenizer = RegexpTokenizer(r'[a-zA-Z]\w*') #Método do nltk para considerar somente letras e retirar pontuação
tokens_false = tokenizer.tokenize(corpus_false_unicode) #Método do nltk para tokenizar palavras

tokens_false_sem_stopwords = []
for token in tokens_false:
  if token.lower() not in stopwords: # Remove as stopwords
    tokens_false_sem_stopwords.append(token.lower()) # Coloca os tokens em minúsculas, o que é imporante para a frequência

#print(tokens_false_sem_stopwords)
frequencia_false = nltk.FreqDist(tokens_false_sem_stopwords)
frequencia_false.most_common(15)

In [ ]:
len(corpus_false)

58671

In [ ]:
#Números calculados pela contagem total de palavras presentes no texto - Falso

n_words = len(tokens_false_sem_stopwords)
frequencia_false_relativa = list(map(lambda x: (x[0], x[1]/n_words), frequencia_false.most_common()))
frequencia_false_relativa
#sum([x[1] for x in frequencia_false_relativa])

# **Etapa 3 - N-gramas**

**3.1)** N-gramas das notícias **VERDADEIRAS**


In [ ]:
from nltk import ngrams # Utilizando o método de extração de n-gramas para o corpus COM stopwords
list(ngrams(tokens_true,3))
#list(ngrams(tokens_true,4))
#list(ngrams(tokens_true,5))
#list(ngrams(tokens_true,6))

**3.1.1)** N-gramas das notícias **VERDADEIRAS (sem stopwords)**

In [ ]:
from nltk import ngrams # Utilizando o método de extração de n-gramas para o corpus SEM stopwords
list(ngrams(tokens_true_sem_stopwords,3))
#list(ngrams(tokens_true_sem_stopwords,4))
#list(ngrams(tokens_true_sem_stopwords,5))
#list(ngrams(tokens_true_sem_stopwords,6))

**3.2)** N-gramas das notícias **FALSAS**


In [ ]:
from nltk import ngrams # Utilizando o método de extração de n-gramas para o corpus COM stopwords
#list(ngrams(tokens_false,3))
#list(ngrams(tokens_false,4))
#list(ngrams(tokens_false,5))
list(ngrams(tokens_false,6))

**3.2.1)** N-gramas das notícias **FALSAS (sem stopwords)**

In [ ]:
from nltk import ngrams # Utilizando o método de extração de n-gramas para o corpus SEM stopwords
list(ngrams(tokens_false_sem_stopwords,3))
#list(ngrams(tokens_false_sem_stopwords,4))
#list(ngrams(tokens_false_sem_stopwords,5))
#list(ngrams(tokens_false_sem_stopwords,6))

# **Etapa 4 - Etiquetadores**

**4.1)** Notícias **VERDADEIRAS**

In [ ]:
from nltk.corpus import mac_morpho
from nltk.tag import UnigramTagger

# Corpus verdadeiro
tokens_true = nltk.word_tokenize(corpus_true_unicode)
sentencas_treino_true = mac_morpho.tagged_sents()
# Função etiquetador
etiquetador_true = UnigramTagger(sentencas_treino_true)
etiquetado_true = etiquetador_true.tag(tokens_true)

etiquetado_true



**4.2** - Notícias **FALSAS**

In [ ]:
from nltk.corpus import mac_morpho
from nltk.tag import UnigramTagger

# Corpus falso
tokens_false = nltk.word_tokenize(corpus_false_unicode)
sentencas_treino_false = mac_morpho.tagged_sents()
# Função etiquetador
etiquetador_false = UnigramTagger(sentencas_treino_false)
etiquetado_false = etiquetador_false.tag(tokens_false)

etiquetado_false

# **Vetorização**


In [ ]:
#Vetorizando Corpus verdadeiro
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(corpus_true)
Vetor = count_vect.get_feature_names_out()

#Imprimindo o vetor
print(Vetor)


['000' '03' '060' ... 'único' 'úteis' 'útero']


In [ ]:
#Analisando Primeiros Valores núméricos e identificado que são números nas noticias "5.000 casos"
print(Vetor[0])

000


In [ ]:
#Verificado que na posição 100 do array possui o número 000 que remete ao "5.000"
VetorVerdadeiro = X_train_counts.toarray()
print(vetorVerdadeiro[100])

[1 0 0 ... 0 0 0]


In [ ]:
#Tamanho vetor Corpus Verdadeiro
tamanho = vetorVerdadeiro.size
print(tamanho)

214704


In [ ]:
#Tokenizando com 
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(5, 5))
X2 = vectorizer2.fit_transform(corpus_true)
vectorizer2.get_feature_names_out()



array(['000 testes em apenas 24', '03 início de testes de',
       '060 mortes se somarmos 2009', ...,
       'único para quarentena separando diariamente',
       'úteis para contabilizar as mortes',
       'útero criança nasceu junto de'], dtype=object)

In [ ]:
print(X2.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
